name: lynx-js/eco-ci
description: "This Github action scans the current pr thread to check if there are command in comments"
inputs:
  token:
    description: token
    required: false
    default: ${{ github.token }}
runs:
  using: "node20"
  main: "index.js"
